### ISSUE TITLE
claimForgottenParcel allows anyone to steal "forgotten" parcels

### ISSUE THREAD

**Issue by dafky2000** [decentraland/land#1]
I am still new to Solidity so forgive me if I missed something obvious but....

In LAND.sol -> claimForgottenParcel there is no verification other than that the token is already owned and it hasn't been pinged in over a year.

Anyone can claim forgotten tokens for free? Or is it supposed to "require(msg.sender == claimContract);"?

**Comment by eordano** [comment]
Thanks! Yes, `require(msg.sender == claimContract)` as you suggested is the way to go!
