### ISSUE TITLE
About Estate 

### ISSUE THREAD

**Issue by VieYang** [decentraland/land#155]
From the docs of FAQ about [What is an Estate?](https://docs.decentraland.org/decentraland/faq/#what-is-an-estate)

`An estate is an association of two or more directly adjacent parcels of LAND. These parcels must be directly adjacent and cannot be separated by a road, plaza or any other parcel. `

But, from the code 

https://github.com/decentraland/land/blob/7cd58341007d1d8884a22e16a726e133405b3bac/contracts/land/LANDRegistry.sol#L400

 two non-adjacent parcels can also be combined into one estate. 

Is there something wrong with me?

**Comment by nachomazzara** [comment]
It is a functionality and UI constraint. You can do Estates with any shape by using directly the smart contract but you will have some issues creating a scene between them.

**Comment by VieYang** [comment]
ok, thank you.
